### ISSUE TITLE
Investigate timeout failures for eyeshade-consumer

### ISSUE THREAD

**Issue by OAuthBringer** [brave-intl/bat-ledger#1057]
Running the stack locally I'm getting this error running the kafka consumer. https://github.com/edenhill/librdkafka/issues/3292

I've traced the commit history back to when this error first emerged and can say confidently it is not related to any source code changes.  I suspect this may be related to the underlying kafka dependencies and this may actually be a real bug.  Not sure how to check if this is impacting production.

**Comment by OAuthBringer** [comment]
We are using `node-sinek` to handle the kafka consumer.  I can confirm that the kafka consumer is failing to connect to kafka locally in docker.

**Comment by OAuthBringer** [comment]
Kafka image is dying locally

```
kafka exited with code 137
```

It's never starting healthy.

**Comment by OAuthBringer** [comment]
eyeshade consumer is in infinite death cycling in local context and CI/CD

```
eyeshade-consumer  | 2022-03-15T21:09:05.762Z sinek:nconsumer:debug [thrd:app]: Configuration property socket.blocking.max.ms is deprecated: No longer used.
eyeshade-consumer  | 2022-03-15T21:09:05.762Z sinek:nconsumer:debug [thrd:app]: Configuration property socket.blocking.max.ms is deprecated: No longer used.
eyeshade-consumer  | 2022-03-15T21:09:05.763Z sinek:nconsumer:debug [thrd:app]: Configuration property socket.blocking.max.ms is deprecated: No longer used.
eyeshade-consumer  | { LibrdKafkaError: broker transport failure
eyeshade-consumer  |     at Function.createLibrdkafkaError [as create] (/usr/src/app/node_modules/node-rdkafka/lib/error.js:334:10)
eyeshade-consumer  |     at /usr/src/app/node_modules/node-rdkafka/lib/client.js:339:28
eyeshade-consumer  | From previous event:
eyeshade-consumer  |     at NConsumer._connectInFlow (/usr/src/app/node_modules/sinek/lib/librdkafka/NConsumer.js:237:12)
eyeshade-consumer  |     at NConsumer.connect (/usr/src/app/node_modules/sinek/lib/librdkafka/NConsumer.js:202:17)
eyeshade-consumer  |     at Promise.all.Object.keys.map (/usr/src/app/bat-utils/lib/runtime-kafka.js:145:22)
eyeshade-consumer  |     at Array.map (<anonymous>)
eyeshade-consumer  |     at Kafka.consume (/usr/src/app/bat-utils/lib/runtime-kafka.js:142:56)
eyeshade-consumer  |     at Object.<anonymous> (/usr/src/app/eyeshade/consumer.js:36:15)
eyeshade-consumer  |     at Module._compile (internal/modules/cjs/loader.js:816:30)
eyeshade-consumer  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
eyeshade-consumer  |     at Module.load (internal/modules/cjs/loader.js:685:32)
eyeshade-consumer  |     at Function.Module._load (internal/modules/cjs/loader.js:620:12)
eyeshade-consumer  |     at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
eyeshade-consumer  |     at internal/main/run_main_module.js:21:11
eyeshade-consumer  |   origin: 'local',
eyeshade-consumer  |   message: 'broker transport failure',
eyeshade-consumer  |   code: -195,
eyeshade-consumer  |   errno: -195 }
eyeshade-consumer  | 2022-03-15T21:09:05.764Z sinek:nconsumer:debug [thrd:app]: Configuration property socket.blocking.max.ms is deprecated: No longer used.
eyeshade-consumer exited with code 0
```

**Comment by tsmartt** [comment]
Will take a look, thanks for the report!

**Comment by tsmartt** [comment]
Removed SSL locally and the integration tests pass, as well as CI. We need to add it back when we switch to a new client, but good for now.
